import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";
import type { RouterType } from "./projectDetect.js";

const IMPORT_STATEMENT = 'import { NextPulse } from "@forgefoundry/nextpulse";';

export function hasImport(src: string): boolean {
  return /from\s+["']@forgefoundry\/nextpulse["']/.test(src);
}

export function hasComponent(src: string): boolean {
  return /<NextPulse\b/.test(src);
}

export function insertImport(src: string): string {
  if (hasImport(src)) return src;
  // Insert after last import (if any), else at top
  const importRe = /(^|\n)(import[\s\S]*?;)(?![\s\S]*\bimport\b)/m;
  const line = `${IMPORT_STATEMENT}\n`;
  if (importRe.test(src)) return src.replace(importRe, (m) => m + "\n" + line);
  return line + src;
}

export function insertComponent(src: string, router: "app" | "pages", props?: Record<string, string>): string {
  if (hasComponent(src)) return src;
  
  // Build props string for JSX attributes
  const propsStr = props && Object.keys(props).length > 0
    ? " " + Object.entries(props)
        .map(([key, value]) => `${key}="${value}"`)
        .join(" ")
    : "";
  
  const dev = `{process.env.NODE_ENV === "development" && <NextPulse${propsStr} />}`;
  if (router === "app") {
    // try to place before closing </body>
    const bodyClose = /<\/body>/i;
    if (bodyClose.test(src)) return src.replace(bodyClose, `${dev}\n      </body>`);
  }
  // generic: append inside the returned JSX before the final ')'
  return src.replace(/return\s*\(([\s\S]*?)\)\s*;/m, (full, inner) => {
    return full.replace(inner, `${inner}\n    ${dev}`);
  });
}

/**
 * Inject NextPulse into entry file
 * Idempotent: skips if both import and component already exist
 */
export function injectIntoEntryFile(
  entryFile: string,
  routerType: RouterType,
  props?: Record<string, string>
): void {
  if (!existsSync(entryFile)) {
    throw new Error(`Entry file not found: ${entryFile}`);
  }

  let content = readFileSync(entryFile, "utf-8");

  // Idempotency check: if both import and component exist, skip
  if (hasImport(content) && hasComponent(content)) {
    return;
  }

  // Add import if not present
  if (!hasImport(content)) {
    content = insertImport(content);
  }

  // Add component based on router type if not present
  if (!hasComponent(content)) {
    if (routerType === "app") {
      content = insertComponent(content, "app", props);
    } else if (routerType === "pages") {
      content = insertComponent(content, "pages", props);
    }
  }

  writeFileSync(entryFile, content, "utf-8");
}

/**
 * Create minimal App Router layout if it doesn't exist
 */
export function createMinimalAppLayout(projectRoot: string, props?: Record<string, string>): string {
  const layoutPath = join(projectRoot, "app", "layout.tsx");
  const layoutDir = join(projectRoot, "app");

  if (!existsSync(layoutDir)) {
    mkdirSync(layoutDir, { recursive: true });
  }

  // Build props string for JSX attributes
  const propsStr = props && Object.keys(props).length > 0
    ? " " + Object.entries(props)
        .map(([key, value]) => `${key}="${value}"`)
        .join(" ")
    : "";
  
  const dev = `{process.env.NODE_ENV === "development" && <NextPulse${propsStr} />}`;

  const content = `import type { Metadata } from "next";
${IMPORT_STATEMENT}

export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children}
        ${dev}
      </body>
    </html>
  );
}
`;

  writeFileSync(layoutPath, content, "utf-8");
  return layoutPath;
}
