/**
 * Template strings for API routes to be generated in user's Next.js project
 * All React components now live in the nextpulse package under src/runtime/
 */

/**
 * App Router: API route to serve metadata from .nextpulse/metadata.json
 */
export const API_METADATA_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve metadata from .nextpulse/metadata.json
 */

import { NextResponse } from "next/server";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

export async function GET() {
  try {
    // Read metadata from .nextpulse/metadata.json
    const metadataPath = join(process.cwd(), ".nextpulse/metadata.json");

    if (!existsSync(metadataPath)) {
      return NextResponse.json(
        { error: "Metadata file not found" },
        { status: 404 }
      );
    }

    const metadata = JSON.parse(readFileSync(metadataPath, "utf-8"));
    return NextResponse.json(metadata);
  } catch (error) {
    console.error("[nextpulse] Failed to load metadata:", error);
    return NextResponse.json(
      { error: "Failed to load metadata" },
      { status: 500 }
    );
  }
}

export const dynamic = "force-dynamic";
`;

/**
 * Pages Router: API route to serve metadata
 */
export const PAGES_API_METADATA_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve metadata from .nextpulse/metadata.json
 */

import type { NextApiRequest, NextApiResponse } from "next";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    return res.status(405).end();
  }

  try {
    // Read metadata from .nextpulse/metadata.json
    const metadataPath = join(process.cwd(), ".nextpulse/metadata.json");

    if (!existsSync(metadataPath)) {
      return res.status(404).json({ error: "Metadata file not found" });
    }

    const metadata = JSON.parse(readFileSync(metadataPath, "utf-8"));
    return res.json(metadata);
  } catch (error) {
    console.error("[nextpulse] Failed to load metadata:", error);
    return res.status(500).json({ error: "Failed to load metadata" });
  }
}
`;

/**
 * App Router: API route to serve config from nextpulse.config.json
 */
export const API_CONFIG_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve runtime config from nextpulse.config.json
 */

import { NextResponse } from "next/server";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

export async function GET() {
  try {
    const configPath = join(process.cwd(), "nextpulse.config.json");

    if (!existsSync(configPath)) {
      return NextResponse.json({ overlayPosition: "bottomRight" });
    }

    const config = JSON.parse(readFileSync(configPath, "utf-8"));

    // Only return safe config values (client-side safe)
    return NextResponse.json({
      overlayPosition: config.overlayPosition || "bottomRight",
    });
  } catch (error) {
    return NextResponse.json({ overlayPosition: "bottomRight" });
  }
}

export const dynamic = "force-dynamic";
`;

/**
 * Pages Router: API route to serve config
 */
export const PAGES_API_CONFIG_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve runtime config from nextpulse.config.json
 */

import type { NextApiRequest, NextApiResponse } from "next";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    return res.status(405).end();
  }

  try {
    const configPath = join(process.cwd(), "nextpulse.config.json");

    if (!existsSync(configPath)) {
      return res.json({ overlayPosition: "bottomRight" });
    }

    const config = JSON.parse(readFileSync(configPath, "utf-8"));

    // Only return safe config values (client-side safe)
    return res.json({
      overlayPosition: config.overlayPosition || "bottomRight",
    });
  } catch (error) {
    return res.json({ overlayPosition: "bottomRight" });
  }
}
`;

/**
 * Get API route templates for App Router
 */
export function getAppRouterApiTemplates(): Record<string, string> {
  return {
    "app/api/nextpulse/metadata/route.ts": API_METADATA_ROUTE_TEMPLATE,
    "app/api/nextpulse/config/route.ts": API_CONFIG_ROUTE_TEMPLATE,
  };
}

/**
 * Get API route templates for Pages Router
 */
export function getPagesRouterApiTemplates(): Record<string, string> {
  return {
    "pages/api/nextpulse/metadata.ts": PAGES_API_METADATA_ROUTE_TEMPLATE,
    "pages/api/nextpulse/config.ts": PAGES_API_CONFIG_ROUTE_TEMPLATE,
  };
}
