/**
 * Template strings for API routes to be generated in user's Next.js project
 * All React components now live in the nextpulse package under src/runtime/
 */

/**
 * App Router: API route to serve metadata from .nextpulse/metadata.json
 */
export const API_METADATA_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve metadata from .nextpulse/metadata.json
 */

import { NextResponse } from "next/server";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

export async function GET() {
  try {
    // Read metadata from .nextpulse/metadata.json
    const metadataPath = join(process.cwd(), ".nextpulse/metadata.json");

    if (!existsSync(metadataPath)) {
      return NextResponse.json(
        { error: "Metadata file not found" },
        { status: 404 }
      );
    }

    const metadata = JSON.parse(readFileSync(metadataPath, "utf-8"));
    return NextResponse.json(metadata);
  } catch (error) {
    console.error("[nextpulse] Failed to load metadata:", error);
    return NextResponse.json(
      { error: "Failed to load metadata" },
      { status: 500 }
    );
  }
}

export const dynamic = "force-dynamic";
`;

/**
 * Pages Router: API route to serve metadata
 */
export const PAGES_API_METADATA_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve metadata from .nextpulse/metadata.json
 */

import type { NextApiRequest, NextApiResponse } from "next";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    return res.status(405).end();
  }

  try {
    // Read metadata from .nextpulse/metadata.json
    const metadataPath = join(process.cwd(), ".nextpulse/metadata.json");

    if (!existsSync(metadataPath)) {
      return res.status(404).json({ error: "Metadata file not found" });
    }

    const metadata = JSON.parse(readFileSync(metadataPath, "utf-8"));
    return res.json(metadata);
  } catch (error) {
    console.error("[nextpulse] Failed to load metadata:", error);
    return res.status(500).json({ error: "Failed to load metadata" });
  }
}
`;

/**
 * App Router: API route to serve config from nextpulse.config.json
 */
export const API_CONFIG_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve runtime config from nextpulse.config.json
 */

import { NextResponse } from "next/server";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

export async function GET() {
  try {
    const configPath = join(process.cwd(), "nextpulse.config.json");

    if (!existsSync(configPath)) {
      return NextResponse.json({ overlayPosition: "bottomRight" });
    }

    const config = JSON.parse(readFileSync(configPath, "utf-8"));

    // Only return safe config values (client-side safe)
    return NextResponse.json({
      overlayPosition: config.overlayPosition || "bottomRight",
    });
  } catch (error) {
    return NextResponse.json({ overlayPosition: "bottomRight" });
  }
}

export const dynamic = "force-dynamic";
`;

/**
 * Pages Router: API route to serve config
 */
export const PAGES_API_CONFIG_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve runtime config from nextpulse.config.json
 */

import type { NextApiRequest, NextApiResponse } from "next";
import { readFileSync, existsSync } from "fs";
import { join } from "path";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    return res.status(405).end();
  }

  try {
    const configPath = join(process.cwd(), "nextpulse.config.json");

    if (!existsSync(configPath)) {
      return res.json({ overlayPosition: "bottomRight" });
    }

    const config = JSON.parse(readFileSync(configPath, "utf-8"));

    // Only return safe config values (client-side safe)
    return res.json({
      overlayPosition: config.overlayPosition || "bottomRight",
    });
  } catch (error) {
    return res.json({ overlayPosition: "bottomRight" });
  }
}
`;

/**
 * App Router: API route to serve runtime snapshot
 */
export const API_RUNTIME_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve runtime snapshot data
 */

import { NextResponse } from "next/server";
import { getRuntimeSnapshot } from "@forgefoundry/nextpulse/instrumentation";

export async function GET() {
  try {
    const snapshot = getRuntimeSnapshot();
    return NextResponse.json(snapshot);
  } catch (error) {
    console.error("[nextpulse] Failed to get runtime snapshot:", error);
    return NextResponse.json(
      { error: "Failed to get runtime snapshot" },
      { status: 500 }
    );
  }
}

export const dynamic = "force-dynamic";
`;

/**
 * App Router: API route to serve bundle information
 */
export const API_BUNDLES_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve bundle information from .next/ directory
 */

import { NextResponse } from "next/server";
import { scanBundles } from "@forgefoundry/nextpulse/instrumentation";

export async function GET() {
  try {
    const projectRoot = process.cwd();
    const bundles = scanBundles(projectRoot);
    
    if (bundles === null) {
      return NextResponse.json(
        { error: "Bundle information not available. Build the project first." },
        { status: 404 }
      );
    }
    
    return NextResponse.json(bundles);
  } catch (error) {
    console.error("[nextpulse] Failed to scan bundles:", error);
    return NextResponse.json(
      { error: "Failed to scan bundles" },
      { status: 500 }
    );
  }
}

export const dynamic = "force-dynamic";
`;

/**
 * App Router: API route to serve error and log snapshot
 */
export const API_ERRORS_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve error and log snapshot data
 */

import { NextResponse } from "next/server";
import { getErrorLogSnapshot } from "@forgefoundry/nextpulse/instrumentation";

export async function GET() {
  try {
    const snapshot = getErrorLogSnapshot();
    return NextResponse.json(snapshot);
  } catch (error) {
    console.error("[nextpulse] Failed to get error log snapshot:", error);
    return NextResponse.json(
      { error: "Failed to get error log snapshot" },
      { status: 500 }
    );
  }
}

export const dynamic = "force-dynamic";
`;

/**
 * Pages Router: API route to serve runtime snapshot
 */
export const PAGES_API_RUNTIME_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve runtime snapshot data
 */

import type { NextApiRequest, NextApiResponse } from "next";
import { getRuntimeSnapshot } from "@forgefoundry/nextpulse/instrumentation";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    return res.status(405).end();
  }

  try {
    const snapshot = getRuntimeSnapshot();
    return res.json(snapshot);
  } catch (error) {
    console.error("[nextpulse] Failed to get runtime snapshot:", error);
    return res.status(500).json({ error: "Failed to get runtime snapshot" });
  }
}
`;

/**
 * Pages Router: API route to serve bundle information
 */
export const PAGES_API_BUNDLES_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve bundle information from .next/ directory
 */

import type { NextApiRequest, NextApiResponse } from "next";
import { scanBundles } from "@forgefoundry/nextpulse/instrumentation";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    return res.status(405).end();
  }

  try {
    const projectRoot = process.cwd();
    const bundles = scanBundles(projectRoot);
    
    if (bundles === null) {
      return res.status(404).json({
        error: "Bundle information not available. Build the project first.",
      });
    }
    
    return res.json(bundles);
  } catch (error) {
    console.error("[nextpulse] Failed to scan bundles:", error);
    return res.status(500).json({ error: "Failed to scan bundles" });
  }
}
`;

/**
 * Pages Router: API route to serve error and log snapshot
 */
export const PAGES_API_ERRORS_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve error and log snapshot data
 */

import type { NextApiRequest, NextApiResponse } from "next";
import { getErrorLogSnapshot } from "@forgefoundry/nextpulse/instrumentation";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    return res.status(405).end();
  }

  try {
    const snapshot = getErrorLogSnapshot();
    return res.json(snapshot);
  } catch (error) {
    console.error("[nextpulse] Failed to get error log snapshot:", error);
    return res.status(500).json({ error: "Failed to get error log snapshot" });
  }
}
`;

/**
 * App Router: API route to serve complete diagnostics snapshot
 */
export const API_DIAGNOSTICS_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve complete diagnostics snapshot
 */

import { NextResponse } from "next/server";
import { buildDiagnosticsSnapshot } from "@forgefoundry/nextpulse/diagnostics";

export async function GET() {
  try {
    const projectRoot = process.cwd();
    const snapshot = buildDiagnosticsSnapshot(projectRoot);
    return NextResponse.json(snapshot);
  } catch (error) {
    console.error("[nextpulse] Failed to build diagnostics snapshot:", error);
    return NextResponse.json(
      { error: "Failed to build diagnostics snapshot" },
      { status: 500 }
    );
  }
}

export const dynamic = "force-dynamic";
`;

/**
 * Pages Router: API route to serve complete diagnostics snapshot
 */
export const PAGES_API_DIAGNOSTICS_ROUTE_TEMPLATE = `/**
 * Auto-generated by nextpulse init
 * API route to serve complete diagnostics snapshot
 */

import type { NextApiRequest, NextApiResponse } from "next";
import { buildDiagnosticsSnapshot } from "@forgefoundry/nextpulse/diagnostics";

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== "GET") {
    return res.status(405).end();
  }

  try {
    const projectRoot = process.cwd();
    const snapshot = buildDiagnosticsSnapshot(projectRoot);
    return res.json(snapshot);
  } catch (error) {
    console.error("[nextpulse] Failed to build diagnostics snapshot:", error);
    return res.status(500).json({ error: "Failed to build diagnostics snapshot" });
  }
}
`;

/**
 * Get API route templates for App Router
 */
export function getAppRouterApiTemplates(): Record<string, string> {
  return {
    "app/api/nextpulse/metadata/route.ts": API_METADATA_ROUTE_TEMPLATE,
    "app/api/nextpulse/config/route.ts": API_CONFIG_ROUTE_TEMPLATE,
    "app/api/nextpulse/runtime/route.ts": API_RUNTIME_ROUTE_TEMPLATE,
    "app/api/nextpulse/bundles/route.ts": API_BUNDLES_ROUTE_TEMPLATE,
    "app/api/nextpulse/errors/route.ts": API_ERRORS_ROUTE_TEMPLATE,
    "app/api/nextpulse/diagnostics/route.ts": API_DIAGNOSTICS_ROUTE_TEMPLATE,
  };
}

/**
 * Get API route templates for Pages Router
 */
export function getPagesRouterApiTemplates(): Record<string, string> {
  return {
    "pages/api/nextpulse/metadata.ts": PAGES_API_METADATA_ROUTE_TEMPLATE,
    "pages/api/nextpulse/config.ts": PAGES_API_CONFIG_ROUTE_TEMPLATE,
    "pages/api/nextpulse/runtime.ts": PAGES_API_RUNTIME_ROUTE_TEMPLATE,
    "pages/api/nextpulse/bundles.ts": PAGES_API_BUNDLES_ROUTE_TEMPLATE,
    "pages/api/nextpulse/errors.ts": PAGES_API_ERRORS_ROUTE_TEMPLATE,
    "pages/api/nextpulse/diagnostics.ts": PAGES_API_DIAGNOSTICS_ROUTE_TEMPLATE,
  };
}
